export const theme = {
    colors: {
        primaryColor: "#000",
        white: "#fff",
        bodyColor: "#f6fcff",
        footerBackground: "#edf3f6",
        gray: "#ccc",
        success: "#04a453",
        danger: "#a40404",
        lightGray: "#eee",
    },
    font: {
        family: {
            default: "'Montserrat', sans-serif",
        },
        sizes: {
            xsmall: "0.6em",
            small: "0.8em",
            default: "1em",
            medium: "1.2em",
            large: "1.4em",
            xlarge: "1.7em",
            xxlarge: "2em",
            huge: "2.4em",
            xhuge: "2.9em",
        },
        line_height: {
            h1: "110%",
            h2: "110%",
            h3: "110%",
            h4: "120%",
            h5: "120%",
            h6: "120%",
            default: "150%",
            small: "150%",
        },
    },
    media: {
        lteMedium: "(max-width: 768px)",
    },
    spacings: {
        xsmall: "0.6em",
        small: "0.8em",
        default: "1em",
        medium: "1.2em",
        large: "1.4em",
        xlarge: "1.7em",
        xxlarge: "2em",
        huge: "2.4em",
        xhuge: "2.9em",
    },
    transition: {
        tran_03: "all 300ms ease-in-out",
        tran_05: "all 500ms ease-in-out",
    },
};
